name: 'continue-on-error Comment'
description: 'GitHub action to add comment when a continue-on-error job fails'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  test-id:
    description: 'Identifier of the test'
  outcome:
    description: 'The outcome of the job'
  bot-user:
    description: 'The username for the bot that posts the comment'
    required: false
    default: 'github-actions[bot]'
runs:
  using: 'node16'
  main: 'dist/index.js'
  pre: 'pre-dist/index.js'