name: 'continue-on-error Comment'
description: 'GitHub action to add comment when a continue-on-error job fails'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  test-id:
    description: 'Identifier of the test'
  outcome:
    description: 'The outcome of the job'
runs:
  using: 'node16'
  main: 'dist/index.js'
  pre: 'pre-dist/index.js'